spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/IdleDev?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug
          datasource:
            init:
              ScriptUtils: debug
