server:
  port: 8080

spring:
  datasource:
    hikari:
      username: root
      password: 9132wjddus
      jdbc-url: jdbc:mysql://localhost:3306/Idle_DB
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.data.jdbc.core.JdbcAggregateTemplate: DEBUG
