name: Idle Backend Project CI/CD build
on:
  push:
    branches:
      - be-main
  pull_request:
    branches:
      - be-develop
      - be-main
jobs:
  
  test:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./backend

      - name: Test with Gradle
        run: ./gradlew test
        working-directory: ./backend

      - name: Jacoco Test Converage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          title: 📝 Test Coverage Report
          paths: ${{ github.workspace }}/backend/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 50
  
  deploy:
    if: ${{github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./backend/src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.EC2_MYSQL_URL }}
          spring.datasource.username: ${{ secrets.EC2_MYSQL_USERNAME }}
          spring.datasource.password: ${{ secrets.EC2_MYSQL_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./backend

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./backend

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/idle:latest ./backend
          docker images
          docker push ${{ secrets.DOCKER_USERNAME }}/idle:latest
      
      - name: Build and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/idle:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/webserver
            sudo docker-compose up -d
            sudo docker image prune -f
