name: Idle Backend Project CI/CD build
on:
  push:
    branches: 
      - be-main
  pull_request:
    branches: 
      - be-develop
      - be-main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: 11
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./backend
      
      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./backend
      
      - name: Test with Gradle
        run: ./gradlew test
        working-directory: ./backend
  
