name: CI Idle Frontend
on:
  push:
    branches:
      - main
    paths: 'frontend/Idle/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/Idle
    
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Generate build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
        run: |
          aws s3 cp --recursive --regon ap-northeast-2 build s3://${{ secrets.AWS_S3_BUCKET_NAME }}
