name: Idle Backend Project CI/CD build
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - be-develop
      - be-main
jobs:
  
  test:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: 11
         distribution: 'temurin'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./backend
      
      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./backend
      
      - name: Test with Gradle
        run: ./gradlew test
        working-directory: ./backend
        
  deploy:
    if: ${{github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: 11
         distribution: 'temurin'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./backend
      
      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./backend

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Image and Push Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/Idle:latest
      
      - name: Build and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker rm -f idle_1
            sudo docker rmi -f ${{ secrets.DOCKER_USERNAME }}/Idle:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/Idle:latest
            sudo docker run --name=idle_1 \
            --restart unless-stopped \
            -p 8080:8080 \
            -e TZ=Asia/Seoul \
            -d \
            ${{ secrets.DOCKER_USERNAME }}/Idle:latest
            
          
            
            
          
            
          
    
  
